stages:
  - test
  - lint

default:
  image: node:20
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/

lint:
  stage: lint
  script:
    - npm ci --legacy-peer-deps
    - npm run lint
    - npx prettier --check "src/**/*.{js,css}"

test:
  stage: test
  needs: []
  script:
    - npm ci --legacy-peer-deps
    - npm test -- --watchAll=false --ci # runs Jest once and completes (not interactive)
