stages:
  - install
  - lint
  - test
  - build
  - deploy

default:
  image: node:20
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

install:
  stage: install
  script:
    - npm ci --legacy-peer-deps
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

lint:
  stage: lint
  dependencies:
    - install
  script:
    - npm run lint
    - npx prettier --check "src/**/*.{js,css}"

test:
  stage: test
  dependencies:
    - install
  script:
    - npm test -- --watchAll=false --ci --forceExit # runs Jest once and completes (not interactive)

build:
  stage: build
  dependencies:
    - install
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week

deploy_staging:
  stage: deploy
  only:
    - main
  tags:
    - vps-deploy
  script:
    - docker compose -f docker-compose.yaml -f docker-compose.production.yaml up --build -d --remove-orphans
    - docker system prune -f
